sudo: false

before_install: umask 0022

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
  - 2.11.12
  - 2.12.6

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test
  - find $HOME/.sbt -name "*.lock" | xargs rm

jdk:
  - openjdk8
